### PR TITLE
Export language and string tables

### PR DESCRIPTION
**Pull request by dhaavi**
Hello,

Thanks for this great library!
I use it to get icons from exe's.

Additionally, I would like to get the product name too, but there is no way to get that information from outside the package.
So, I added and tested a simple function that returns a full copy of the language and string tables in order to not interfere with any already validated data in there.

Usually, I myself hate to get PRs with changes that were not discussed before - sorry about that if you feel the same way.
I am willing to make changes per your request.

Changes:
- Add Info.Table() to export tables
- Add LangTable.GetMainTranslation() to quickly get main translation

### CODE REVIEW

**Comment by dhaavi** [comment]
Hey @tc-hib, just in case this got lost somewhere - would be nice to know how to move forward. Please just close the PR if you don't want the changes - then I can stop waiting. :smirk:

**Comment by tc-hib** [comment]
Hi,
I'm sorry I had you wait such a long time.
I have been very busy.
This feature is very welcome, and you seem to have implemented it properly.
I'll try to review and merge it before the end of the week.

**Comment by dhaavi** [comment]
Great, thanks!

No problem, I fully understand.
Also, there is no hurry, don't stress yourself because of me.

**Review by tc-hib — APPROVED** [review]
It's all good, thanks.

**Pull request merged**
